empresa/urls.py
from django.urls import include, path

from . import views

urlpatterns = [
    path('nova_empresa/',views.nova_empresa, name='nova_empresa'),
    path('empresas/', views.empresas, name="empresa"),
    path('excluir_empresa/<int:id>', views.excluir_empresa, name="excluir_empresa"),
    path('empresa/<int:id>', views.empresa, name="empresa_unica"),

]

seletive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('empresa.urls')),
    path('vagas/', include('vagas.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vagas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('nova_vaga/', views.nova_vaga, name="nova_vaga"),
    path('vaga/<int:id>', views.vaga, name="vaga"),
    path('nova_tarefa/<int:id_vaga>', views.nova_tarefa, name='nova_tarefa'),
]

empresa/models.py
# Create your models here.
from django.db import models


class Tecnologias(models.Model):
    tecnologia = models.CharField(max_length=30)

    def __str__(self):
        return self.tecnologia

class Empresa(models.Model):
    choices_nicho_mercado = (
        ('M', 'Marketing'),
        ('N', 'Nutrição'),
        ('D', 'Design')
    )
    logo = models.ImageField(upload_to="logo_empresa")
    nome = models.CharField(max_length=30)
    email = models.EmailField()
    cidade = models.CharField(max_length=30)
    tecnologias = models.ManyToManyField(Tecnologias)
    endereco = models.CharField(max_length=60)
    nicho_mercado = models.CharField(max_length=3, choices=choices_nicho_mercado)
    caracteristica_empresa = models.TextField()

    def __str__(self) -> str:
        return self.nome
    
    def qtd_vagas(self):
        return Vagas.objects.filter(empresa__id=self.id).count()

class Vagas(models.Model):
    choices_experiencia = (
        ('J', 'Júnior'),
        ('P', 'Pleno'),
        ('S', 'Sênior')
    )

    choices_status = (
        ('I', 'Interesse'),
        ('C', 'Currículo enviado'),
        ('E', 'Entrevista'),
        ('D', 'Desafio técnico'),
        ('F', 'Finalizado')
    )
    
    empresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=30)
    nivel_experiencia = models.CharField(max_length=2, choices=choices_experiencia)
    data_final = models.DateField()
    email = models.EmailField(null=True)
    status = models.CharField(max_length=30, choices=choices_status)
    tecnologias_dominadas = models.ManyToManyField(Tecnologias)
    tecnologias_estudar = models.ManyToManyField(Tecnologias, related_name='estudar')

    def progresso(self):
        x = [((i+1)*20,j[0]) for i, j in enumerate(self.choices_status)]
        x = list(filter(lambda x: x[1] == self.status, x))[0][0]
        return x

    def __str__(self):
        return self.titulo

vagas/models.py
from django.db import models

from empresa.models import *


# Create your models here.
class Tarefa(models.Model):
    choices_prioridade = (
        ('B', 'Baixa'),
        ('A', 'Alta'),
        ('U', 'Urgente')
    )
    vaga = models.ForeignKey(Vagas, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=30)
    prioridade = models.CharField(max_length=1, choices=choices_prioridade)
    data = models.DateField()
    realizada = models.BooleanField(default=False)

    def __str__(self):
        return self.titulo

empresa/views.py
from django.contrib import messages
from django.contrib.messages import constants
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from .models import *

# Create your views here.


def nova_empresa(request):
    if request.method == "GET":
        techs = Tecnologias.objects.all()
        return render(request, 'nova_empresa.html', {'techs': techs})
    elif request.method == "POST":
        nome = request.POST.get('nome')
        email = request.POST.get('email')
        cidade = request.POST.get('cidade')
        endereco = request.POST.get('endereco')
        nicho = request.POST.get('nicho')
        caracteristicas = request.POST.get('caracteristicas')
        tecnologias = request.POST.getlist('tecnologias')
        logo = request.FILES.get('logo')
        
        if (len(nome.strip()) == 0 or len(email.strip()) == 0 or len(cidade.strip()) == 0 or len(endereco.strip()) == 0 or len(nicho.strip()) == 0 or len(caracteristicas.strip()) == 0 or (not logo)): 
            messages.add_message(request, constants.ERROR, 'Preencha todos os campos')
            return redirect('/home/nova_empresa')

        if logo.size > 100_000_000:
            messages.add_message(request, constants.ERROR, 'A logo da empresa deve ter menos de 10MB')
            return redirect('/home/nova_empresa')

        if nicho not in [i[0] for i in Empresa.choices_nicho_mercado]:
            messages.add_message(request, constants.ERROR, 'Nicho de mercado inválido')
            return redirect('/home/nova_empresa')
        
        empresa = Empresa(logo=logo,
                        nome=nome,
                        email=email,
                        cidade=cidade,
                        endereco=endereco,
                        nicho_mercado=nicho,
                        caracteristica_empresa=caracteristicas)
        empresa.save()
        empresa.tecnologias.add(*tecnologias)
        empresa.save()
        messages.add_message(request, constants.SUCCESS, 'Empresa cadastrada com sucesso')
        return redirect('/home/empresas')

def empresas(request):
    technologias_filtrar = request.GET.get('tecnologias')
    nome_filtrar = request.GET.get('nome')
    empresas = Empresa.objects.all()

    if technologias_filtrar:
        empresas = empresas.filter(tecnologias = technologias_filtrar)
    
    if nome_filtrar:
        empresas = empresas.filter(nome__icontains = nome_filtrar)

    tecnologias = Tecnologias.objects.all()
    return render(request, 'empresa.html', {'empresas': empresas, 'tecnologias': tecnologias})

def excluir_empresa(request, id):
    empresa = Empresa.objects.get(id=id)
    empresa.delete()
    messages.add_message(request, constants.SUCCESS, 'Empresa excluída com sucesso')
    return redirect('/home/empresas')

def empresa(request, id):
    empresa = get_object_or_404(Empresa, id=id)
    empresas = Empresa.objects.all()
    tecnologias = Tecnologias.objects.all()
    vagas = Vagas.objects.filter(empresa_id=id)
    return render(request, 'empresa_unica.html', {'empresa': empresa,
                                            'tecnologias': tecnologias,
                                            'empresas': empresas,
                                            'vagas': vagas})

vagas/views.py
from django.contrib import messages
from django.contrib.messages import constants
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from empresa.models import Vagas

from .models import *


# Create your views here.
def nova_vaga(request):
    if request.method == "POST":
        titulo = request.POST.get('titulo')
        email = request.POST.get('email')
        tecnologias_domina = request.POST.get('tecnologias_domina')
        tecnologias_nao_domina = request.POST.get('tecnologias_nao_domina')
        experiencia = request.POST.get('experiencia')
        data_final = request.POST.get('data_final')
        empresa = request.POST.get('empresa')
        status = request.POST.get('status')

        # TODO: validations

        vaga = Vagas(
                    titulo=titulo,
                    email=email,
                    nivel_experiencia=experiencia,
                    data_final=data_final,
                    empresa_id=empresa,
                    status=status,
        )


        vaga.save()

        vaga.tecnologias_estudar.add(*tecnologias_nao_domina)
        vaga.tecnologias_dominadas.add(*tecnologias_domina)

        vaga.save()
        messages.add_message(request, constants.SUCCESS, 'Vaga criada com sucesso.')
        return redirect(f'/home/empresa/{empresa}')
    elif request.method == "GET":
        raise Http404()


def vaga(request, id):
    vaga = get_object_or_404(Vagas, id=id)
    tarefas = Tarefa.objects.filter(vaga=vaga).filter(realizada=False)
    return render(request, 'vaga.html', {'vaga': vaga,'tarefas': tarefas})

def nova_tarefa(request, id_vaga):
    titulo = request.POST.get('titulo')
    prioridade = request.POST.get("prioridade")
    data = request.POST.get('data')
    
    tarefa = Tarefa(vaga_id=id_vaga,
                    titulo=titulo,
                    prioridade=prioridade,
                    data=data)
    tarefa.save()
    messages.add_message(request, constants.SUCCESS, 'Tarefa criada com sucesso')
    return redirect(f'/vagas/vaga/{id_vaga}')

empresa/templates/empresa.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'empresa/css/empresas.css' %}" rel="stylesheet">
{% endblock%}

{% block 'body' %}
    <div class="wrapper">
        <div class="box"> 
            <div class="header-box">
                {% if messages %}
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %}
                <h2 class="titulo">Gerenciar empresas</h2>
                <a class="btn-nova-empresa">Nova empresa</a>
            </div>
            <div class="borda-box"></div>
            <div class="body-box">
            
                <form action="{% url 'empresa' %}" method="GET">{% csrf_token %}
                <div class="row">
                    
                        <div class="col-md-5">
                            <input type="text" placeholder="Busque pelo nome" class="form-control" name="nome">
                        </div>

                        <div class="col-md-4">
                            <select class="form-select" name="tecnologias">
                                {% for tech in tecnologias%}
                                    <option value="{{tech.id}}">{{tech}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    
                    <div class="col-md-3">
                        <input type="submit" value="FILTRAR" class="btn btn-lg btn-orange">
                    </div>
                </div>
                </form>

                <table class="tabela" cellpadding="20">
                    <tr>
                        <th>Nome</th>
                        <th>Endereço</th>
                        <th>Tecnologias usadas</th>
                        <th>Quantidade de vagas</th>
                        <th>Ação</th>
                    </tr>

                    
                    {% for empresa in empresas%}
                    <tr class="tabela-linha">
                        <td><a href="{% url 'empresa_unica' empresa.id%}">{{empresa.nome}}</a></td>
                        <td>{{empresa.endereco}}</td>
                        <td>
                            <select class="form-select">     
                                {% for tech in empresa.tecnologias.all %}
                                    <option>{{tech}}</option>
                                {% endfor %}                               
                                                      
                            </select>
                        </td>
                        <td>
                            {% if empresa.qtd_vagas > 0 %}
                                <img src="{% static 'empresa/img/flag_green.png' %}">
                            {% else %}
                                <img src="{% static 'empresa/img/flag_red.png' %}">
                            {% endif %}
                            &nbsp&nbsp{{empresa.qtd_vagas}}
                        </td>
                        <td>
                            <a href="{% url 'excluir_empresa' empresa.id %}" class="btn-excluir">Excluir empresa</a>
                        </td>
                    </tr>
                {% endfor %}
                    
                </table>
            </div>

        </div>
    </div>

{% endblock%}

empresa/templates/empresa_unica.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link href="{% static 'empresa/css/empresa.css' %}" rel="stylesheet">
{% endblock%}


{% block 'body' %}

    
    <br>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <br>
                <section class="alert {{message.tags}}">
                    {{message}}
                </section>
            {% endfor %}
        {% endif %}    
        <div class="row">
            <div class="col-md-3">
                <img width="100%" src="{{empresa.logo.url}}">
            </div>

            <div class="col-md">
                <h1 class="titulo">{{empresa.nome}}</h1>
                <p class="paragrafo">{{empresa.endereco}}</p>
            </div>



        </div>
        <br>
        <div class="row">
            <div class="col-md-6">
                <label>Nicho de mercado:</label>
                <input disabled type="text" class="form-control" value="{{empresa.get_nicho_mercado_display}}">
            </div>

            <div class="col-md-3">
                <label>Tecnologias usadas:</label>
                <select class="form-select">   
                    {% for tech in empresa.tecnologias.all %}
                    <option>{{tech}}</option>
                    {% endfor %}
                </select>
                
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-7">
                <label>Características da empresa:</label>
                <textarea disabled class="form-control">{{empresa.caracteristica_empresa}}</textarea>
            </div>

            <div class="col-md-3">
                
                
            </div>
        </div>

        <hr>

        <a data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-lg btn-orange">Nova vaga</a>

        <div class="row">
            {% for vaga in vagas %}
                <div class="col-md">

                <div class="box-vagas">
                <div class="header-vagas">
                <a href="{% url 'vaga' vaga.id%}">{{vaga.titulo}}</a>
                </div>

                <div class="body-vagas">
                <div class="row">
                <div class="col-md">
                    <label class="paragrafo">Nível:</label>
                    <br>        
                    <label class="paragrafo paragrafo-orange">{{vaga.get_nivel_experiencia_display}}</label>                           
                </div>

                <div class="col-md">
                    <label class="paragrafo">Status <img src="{% static 'empresa/img/flag_green.png' %}"></label>
                    <br>        
                    <label class="paragrafo paragrafo-orange">{{vaga.get_status_display}}</label>                           
                </div>

                </div>
                </div>

                </div>

                </div>
            {% endfor %}
        </div>

    </div>
    <br>
    <br>
    <div class="modal fade modal-lg" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
            <div class="modal-header">
                <h5 style="font-size: 30px" class="modal-title titulo" id="exampleModalLabel">Nova vaga</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'nova_vaga' %}" method="POST">{% csrf_token %}
                    <div class="row">
                        <div class="col-md">
                            <label>Título:</label>
                            <input type="text" name="titulo" class="form-control" placeholder="Digite o título da vaga...">
                        </div>

                        <div class="col-md">
                            <label>Email:</label>
                            <input type="email" name="email" class="form-control" placeholder="email@email.com.br">
                        </div>
                        
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Tecnologias que já domino:</label>
                            <select name="tecnologias_domina" class="form-select" multiple>
                                {% for tech in tecnologias %}
                                    <option value="{{tech.id}}">{{tech}}</option>
                                {% endfor %}

                            </select>
                        </div>

                        <div class="col-md">
                            <label>Tecnologias que não domino:</label>
                            <select name="tecnologias_nao_domina" class="form-select" multiple>
                                {% for tech in tecnologias %}
                                    <option value="{{tech.id}}">{{tech}}</option>
                                {% endfor %}

                            </select>
                        </div>
                        
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Nível de experiência:</label>
                            <select name="experiencia" class="form-select">
                                <option value="J">Júnior</option>
                                <option value="P">Pleno</option>
                                <option value="S">Sênior</option>
                            </select>
                        </div>

                        <div class="col-md">
                            <label>Data final:</label>
                            <input type="date" class="form-control" name="data_final"> 
                            
                        </div>
                        
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Empresa:</label>
                            <select name="empresa" class="form-select">
                                {% for empresa_iter in empresas %}
                                <option {% if empresa_iter.id == empresa.id %}selected{%endif%}  value="{{empresa_iter.id}}">{{empresa_iter}}</option>
                                {% endfor %}
                                                                                                                                 
                            </select>
                        </div>
       
                    </div>

                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Status:</label>
                            <select name="status" class="form-select">     
                                <option value="I">Interesse</option>
                                <option value="C">Currículo enviado</option>    
                                <option value="E">Entrevista</option>    
                                <option value="D">Desafio técnico</option>    
                                <option value="F">Finalizado</option>          
                            </select>
                        </div>
       
                    </div>
                    <br>
                    <input type="submit" value="Nova empresa" class="btn btn-lg btn-orange">

                </form>
            </div>
           
            </div>
        </div>
    </div>
{% endblock %}

empresa/templates/nova_empresa.html
{% extends "base.html" %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'empresa/css/nova_empresa.css' %}">
{% endblock  %}

{% block 'body' %}
    
    <div class="wrapper">
        <div class="box">
            <div class="header">
                <h3 class="titulo">Nova empresa</h3>
            </div><br>
            {% if messages %}
                {% for message in messages %}
                    <section class="alert {{message.tags}}">
                        {{message}}
                    </section>
                {% endfor %}
            {% endif %}
            <div class="body-box">
                <form action="{% url 'nova_empresa' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                        <div class="col-md">
                            <label>Nome:</label>
                            <input type="text" class="form-control" name="nome" placeholder="Digite seu nome...">
                        </div>

                        <div class="col-md">
                            <label>E-mail:</label>
                            <input type="email" class="form-control" name="email" placeholder="email@gmail.com">
                        </div>

                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Cidade:</label>
                            <input type="text" class="form-control" name="cidade" placeholder="Digite a cidade da empresa...">
                        </div>

                        <div class="col-md">
                            <label>Endereço:</label>
                            <input type="text" class="form-control" name="endereco" placeholder="Rua...">
                        </div>

                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Nicho de mercado:</label>
                            <select class="form-control" name="nicho">
                                <option value="M">Marketing</option>
                                <option value="N">Nutrição</option>
                                <option value="D">Design</option>
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Tecnologias usadas:</label>
                            <select class="form-control" name="tecnologias" multiple> 
                                {% for tech in techs %}
                                <option value="{{tech.id}}"></option>
                                {% endfor %}                              
                                
                                
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Característica da empresa:</label>
                            <textarea name="caracteristicas" class="form-control"></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Logo:</label>
                            <input type="file" class="form-control" name="logo">
                        </div>
                    </div>
                    <br>
                    <input type="submit" value="Nova empresa" class="btn btn-lg btn-orange">
                </form>
                
            </div>
        </div>
    </div>


{% endblock%}

templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block 'title' %}{% endblock%}</title>
    <link href="{% static 'base/css/base.css' %}" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet">
    {% block 'head' %}{% endblock%}
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-nav">
        <a class="navbar-brand" href="#">SELETI.VE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

    </nav>
    
    {% block 'body' %}{% endblock%}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

vagas/templates/vaga.html
{% extends 'base.html' %}
{% load static %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'vaga/css/vaga.css' %}"> 
{% endblock %}

{% block 'body' %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
            <br>
                <section class="alert {{message.tags}}">
                    {{message}}
                </section>
            {% endfor %}
        {% endif %}
        <br>
        <h3 class="titulo">{{vaga.titulo}}</h3>
        <p class="titulo2">{{vaga.empresa}}</p>
        <p>Progresso atual</p>
        
        <div style="width: 40%" class="progress">
            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width:  {{vaga.progresso}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>

    <div class="bg2">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <p class="titulo2">Crie uma tarefa</p>
                    <p>Lembre-se de realizar todas suas tarefas com antecedência</p>


                    <form action="{% url 'nova_tarefa' vaga.id %}" method="POST">{% csrf_token %}
                        <label>Título:</label>
                        <input name="titulo" type="text" class="form-control input-tarefa" placeholder="Digite o título da tarefa..."> 
                        <br>
                        <label>Prioridade:</label>
                        <select name="prioridade" class="form-select input-tarefa">
                            <option value="U">Urgente</option>
                            <option value="A">Alta</option>
                            <option value="B">Baixa</option>
                        </select>
                        <br>
                        <label>Data:</label>
                        <input name="data" type="date" class="form-control input-tarefa" placeholder=""> 
                        <br>
                        <input type="submit" value="Nova tarefa" class="btn btn-orange">

                    </form>

                </div>

                <div class="col-md">
                    
                    {% for tarefa in tarefas %}
                        <div class="li-tarefa">
                            <label>{{tarefa.titulo}}</label>
                            <label class="prioridade-bloco">
                                <svg class="prioridade-vermelho" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                            </label>
                            <label class="prioridade-bloco">
                                {{tarefa.data}}
                            </label>
                            <label class="prioridade-bloco">
                                <a href="#" class="btn btn-success">Finalizado</a>
                            </label>
                    
                        </div>
                    {% endfor %}
                    
                        

                        

                    
                    
                </div>

            </div>
        </div>

    </div>

    <div class="container bg3">
        <div class="row">

            <div class="col-md">
                <p class="titulo2">Enviar E-mail</p>
                <p>Envie e-mails para essa vaga por aqui.</p>
            </div>

            <div class="col-md">
                <form>
                    <label>Assunto:</label>
                    <input name="assunto" type="text" class="form-control" placeholder="assunto">
                    <br>
                    <label>Corpo do email:</label>
                    <textarea name="corpo" class="form-control"></textarea>
                    <br>
                    <input type="submit" class="btn btn-orange" value="Enviar">
                </form>
            </div>
        </div>

    </div>


    <div class="bg2">
        <div class="container">
            <div class="row"> 
                <h3 class="titulo">Histórico de e-mails</h3>
                
                    <div class="col-md">

                        <div class="box-email">
                            <div class="header-email">
                                Assunto
                            </div>

                            <div class="body-email">
                                Corpo do email
                            </div>
                            
                        </div>
            
                    </div>
                
                
                  
            </div> 
            
                    
        </div>
    </div>

    <div class="container bg3">
        <div class="row">
            <div class="col-md">
                <p class="titulo2">Tecnologias que domino</p>

                <div class="li-tech">
                    Python

                    <svg class="arrow-right" xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                    </svg>
                </div>

            </div>

            <div class="col-md">
                <p class="titulo2">Preciso estudar</p>

                <div class="li-tech">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                    </svg>
                    Python
                </div>
            </div>
        </div>
    </div>
{% endblock %}